image: node:4.6.1

deploy:
  environment: production
  script:
    - npm install --silent
    - npm run build
    - pip install awscli
    - aws s3 cp ./dist s3://giant-multiplayer-ripoff/ --recursive
  only:
    - master
