image: node:4.6.1

deploy:
  environment: production
  script:
    - npm install --silent
    - npm run build
    - apt-get update
    - apt-get install -y lftp
    - lftp -u $AZURE_DEPLOYMENT_USER,$AZURE_DEPLOYMENT_PASSWORD -e 'mirror -Rp dist /site/wwwroot; quit' ftps://waws-prod-ch1-013.ftp.azurewebsites.windows.net
  only:
    - master
